version: '3'
services:
  sqs:
    image: s12v/elasticmq:latest
    ports:
    - "9324:9324"

  deploy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
    - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
    - "STAGE=development"
    working_dir: /opt/app
    command: >
      sh -c '
      serverless deploy
      '
